GET http://localhost:8080/orders
Accept: application/json

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "products": [
    {
      "productId": 1,
      "amount": 0.5
    },
    {
      "productId": 3,
      "amount": 3.5
    },
    {
      "productId": 4,
      "amount": 5
    }
  ]
}

###
GET http://localhost:8080/orders/afb2b528-ffe2-4ae9-b129-c8be4d13b15c/products
Accept: application/json

###

